apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-ci-cd-deployment
  labels:
    app: web-ci-cd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-ci-cd
  template:
    metadata:
      labels:
        app: web-ci-cd
    spec:
      containers:
      - name: web-ci-cd-container
        image: sahanharshana/web-app:latest
        ports:
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: web-ci-cd-service
spec:
  selector:
    app: web-ci-cd
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  type: NodePort

