apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-ci-cd-deployment
  labels:
    app: web-ci-cd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-ci-cd
  template:
    metadata:
      labels:
        app: web-ci-cd
    spec:
      containers:
      - name: web-ci-cd-container
        image: sahanharshana/web-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-ci-cd-service
spec:
  selector:
    app: web-ci-cd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31338
  externalIPs:
    - 10.0.2.15
  type: NodePort
  externalTrafficPolicy: Local

